### ISSUE TITLE
Suggestion for prerequisites in learning Laravel framework.

### ISSUE THREAD

**Issue by raakesh** [coderplex/learn#20]
Add this https://laracasts.com/series/php-for-beginners to the prerequisites of Learn-Laravel.
Add a section for OOP beginner in the prerequisites, few course that I would like to suggest for this are below.
https://laracasts.com/series/object-oriented-bootcamp-in-php
https://laracasts.com/series/solid-principles-in-php
https://laracasts.com/series/design-patterns-in-php

**Comment by pbteja1998** [comment]
Thanks for your suggestions. In future we want to add PHP curriculum under programming languages and add link to that curriculum as prerequisite to taking Laravel. The resources which you suggested will be added under PHP curriculum. Do you want to contribute to PHP curriculum?

**Comment by pbteja1998** [comment]
If you wish to contribute to the PHP curriculum, follow [this](https://github.com/coderplex/learn/blob/master/web-dev/Backend/laravel/2-curriculum/2-core-larvel/1-MVC-and-routes/0-basic-routing-and-views.md) structure and send a pull request to this repo.

**Comment by raakesh** [comment]
I'll try to create a PHP curriculum.

**Comment by pbteja1998** [comment]
@raakesh  Sure, go on with creating PHP curriculum. Tell me if you need any help in creating the curriculum.

**Comment by raakesh** [comment]
Is there any slack group?

**Comment by pbteja1998** [comment]
No, we use discord as our mode of communication. You can join [here](https://discord.gg/dVnQ2Gf) .
