### ISSUE TITLE
There is no mention of Laravel version in Learn-Laravel section

### ISSUE THREAD

**Issue by raakesh** [coderplex/learn#23]
I think tutorials and videos lessons should be tagged with laravel version.

**Comment by duttakapil** [comment]
@pbteja1998 ?

**Comment by pbteja1998** [comment]
@raakesh Thanks for pointing that out. Right now all videos and tutorials are of version 5.4 . I will add that to the curriculum too.

**Comment by duttakapil** [comment]
@pbteja1998 any updates on this?

**Comment by pbteja1998** [comment]
Just change the main h1 tag from `Roadmap for Laravel` to `Roadmap for Laravel 5.4`.  That should suffice for now. In future, when things related to 5.5 are added, then I will change other things. Right now, everything is related to Laravel 5.4
