### ISSUE TITLE
Links to prerequisite courses

### ISSUE THREAD

**Issue by anandpotukuchi** [coderplex/learn#31]
The "Prerequisite" block in each should have a link to prerequisite courses.

eg: Laravel should have a link to basic front end - HTML & CSS and JS courses AND PHP

**Comment by duttakapil** [comment]
@anandpotukchi can you send a PR, hyperlinked the prerequisite topics from the guides we have available right now?

**Comment by anandpotukuchi** [comment]
Issue invalid in current scenario
