### ISSUE TITLE
Git guide

### ISSUE THREAD

**Issue by anandpotukuchi** [coderplex/learn#38]
This issue is just to make sure that there is no conflict of interest. You can mention me in the comment if you want to work with me.

**Comment by elevenpassin** [comment]
@anandpotukchi Hey, still willing to work on this?

**Comment by anandpotukuchi** [comment]
I'm sorry. I've been busy. And will be. You can do it.

**Comment by elevenpassin** [comment]
@anandpotukchi It's alright, thanks!
