### ISSUE TITLE
create separate repositories for separate Languages

### ISSUE THREAD

**Issue by nihilistdbanana** [coderplex/learn#6]
To be honest, I love the curriculum designs, but I strongly feel  that it would be great to create a repo for each language for accessibility purposes.

**Comment by duttakapil** [comment]
I'm not sure if you're aware, but we will be rendering these curriculum's on our website at https://coderplex.org/learn. The website itself is under construction right now

**Comment by nihilistdbanana** [comment]
So, should I be committing the codes to this repo itself?

**Comment by duttakapil** [comment]
Code for the learn page?

**Comment by nihilistdbanana** [comment]
Yo.

**Comment by duttakapil** [comment]
@vinaypuppal and @M-ZubairAhmed are working on it already. For the moment, I think we'll be pushing it to our /coderplex-website repo, which is the frontend of the website. What code have you exactly written? Do you have it online anywhere?

**Comment by nihilistdbanana** [comment]
https://github.com/lbsrex/Python101

I kinda started this. It's kinda informal.

**Comment by duttakapil** [comment]
This looks good! We can put this up under the Coderplex org on GitHub, but they don't exactly fit with the learn guides we're creating. Have another look at the [Laravel guide](https://github.com/coderplex/learn/blob/master/web-dev/Backend/Learn-Laravel.md) to get a gist of the structure we're following

**Comment by nihilistdbanana** [comment]
I can start writing with the learn guide in mind, and structure my commits accordingly. should I start by adding files to the Python part of the learn repo?

**Comment by duttakapil** [comment]
Yes, go ahead!

**Comment by M-ZubairAhmed** [comment]
@lbsrex we do not plan to make into each repository as such. We will release the road map for how we will incorporate lean in our web app soon.
Also please keep doing your valuable contributions. :+1:
