### ISSUE TITLE
Split each unit of each curriculum into separate .md files

### ISSUE THREAD

**Issue by duttakapil** [coderplex/learn#7]
We need to split each unit in each curriculum into a separate markdown file, so that we can write code that takes these files and renders them on our coderplex.org/learn page. 

Example of a single unit from Laravel curriculum : 
![image](https://user-images.githubusercontent.com/6577624/31491138-eb4cbd4a-af63-11e7-8dc9-5f0f1b7a5e7b.png)

This unit should be it's own .md file. 

Question : How are we going to maintain the order of the units / folder structure? 
@vinaypuppal any ideas?

*edit : 1*
Following subjects curiculum are under special attention -
- Web development
  - Backend
    - [X] Laravel
  - Frontend
    - [ ] Basics
    - [ ] Intermediate
    - [ ] Angular
    - [ ] React
    - [ ] Vue
- [ ] Data science
- [ ] Blockchain

**Comment by pbteja1998** [comment]
1-topic.md
         1-1-subtopic.md
         1-2-subtopic.md
               1-2-1-subsubtopic.md
               1-2-2-subsubtopic.md
         1-3-subtopic.md
2-topic.md
         2-1-subtopic.md

**Comment by M-ZubairAhmed** [comment]
Following subjects curiculum are under special attention -
- Web development
  - Backend
    - [X] Laravel
  - Frontend
    - [ ] Basics
    - [ ] Intermediate
    - [ ] Angular
    - [ ] React
    - [ ] Vue
- [ ] Data science
- [ ] Blockchain

**Comment by vinaypuppal** [comment]
@duttakapil and @M-ZubairAhmed It would be better if we split for example like this
```
laravel
├── 0-preface.md
├── 1-community.md
├── 2-curriculum
│   ├── 0-prerequisites.md
│   ├── 1-introduction-to-mvc.md
│   ├── 2-core-larvel
│   │   ├── 0-installaion.md
│   │   ├── 1-MVC-and-routes
│   │   │   ├── 0-basic-routing-and-views.md
│   │   │   ├── 1-passing-data-to-views.md
│   │   │   ├── 2-database-setup.md
│   │   │   ├── 3-working-with-query-builder.md
│   │   │   ├── 4-eloquent.md
│   │   │   ├── 5-controllers.md
│   │   │   └── 6-route-model-binding.md
│   │   ├── 2-frontend
│   │   │   ├── 0-layouts-and-structures.md
│   │   │   ├── 1-form-requests-and-csrf.md
│   │   │   ├── 2-form-validation.md
│   │   │   ├── 3-rendering.md
│   │   │   ├── 4-laravel-mix.md
│   │   │   └── 5-flash-messages.md
│   │   ├── 3-relationships
│   │   │   ├── 0-eloquent-relationships.md
│   │   │   ├── 1-one-to-many-relationships.md
│   │   │   └── 2-pivot-tables.md
│   │   ├── 4-authentication
│   │   │   ├── 0-scaffold-authentication.md
│   │   │   └── 1-manual-authentication.md
│   │   └── 5-archives
│   │       ├── 0-add-archives.md
│   │       └── 1-view-composers.md
│   ├── 3-advance-larvel
│   │   └── 0-testing-and-seeding.md
│   └── 4-final-project.md
├── 3-additional-resources
├── 4-opensource-projects.md
```

**Comment by M-ZubairAhmed** [comment]
yes and lets use the same template for doing all files splitting which are listed above

**Comment by duttakapil** [comment]
LGTM 👍 @vinaypuppal

**Comment by djsbalakrishnan** [comment]
Will start doing the same for python curriculum.

**Comment by M-ZubairAhmed** [comment]
We are not following this anymore as plans for using static site generator is dropped. Curruculum contributors are requested to follow on the guidelines of [laravel curriculum](https://github.com/coderplex/learn/blob/master/web-dev/Backend/Learn-Laravel.md)
